services:
  Rudy86SchedulerBundleCronController:
    class: CronController
    public: true
    arguments:
    tags: ['controller.service_arguments']
    calls:
      - ['setContainer', ['@service_container']]